name = "soft-field-35b7"
main = "src/worker.js"
compatibility_date = "2023-08-14"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "notify"
database_id = "93e865d4-2281-4208-b7e2-f95b7fe4911c"

[placement]
mode = "smart"
